define: &repo "hercdottech/docker-optimised-fpm-server"
define: &callback ""
define: &name "Docker - PHP FPM Server"

kind: pipeline
type: docker
name: *name

steps:
  - name: Publish Main Image
    image: thegeeklab/drone-docker-buildx:24.1.3
    privileged: true
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PAT
      repo: *repo
      tags:
        - "8.4"
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      branch:
        - main
      event: [push, tag]
